source "https://rubygems.org"

gem "test-kitchen"
gem "kitchen-ansible"
gem "kitchen-docker"
gem "kitchen-inspec"
gem "kitchen-vagrant"
gem "kitchen-sync"
gem "inspec-bin"
gem "winrm"
gem "winrm-fs"
gem "vagrant-winrm"
