source "https://rubygems.org"

gem "test-kitchen", ">= 1.6"
gem "kitchen-ansible", "0.50.1"
gem "kitchen-docker", "2.9.0"
gem "kitchen-inspec", "1.2.0"
gem "kitchen-vagrant", "1.6.0"
gem "kitchen-sync", "2.2.1"
gem "inspec-bin", ">= 4.16.0 "
gem "winrm", "2.3.2"
gem "winrm-fs", "1.3.2"
gem "vagrant-winrm", "0.7.0"
